global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "spring-app"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8888  # 로컬 Spring Boot
    scheme: http
